Pushing vault and SM files to gcs for testing

diff --git a/actions/import-secret/action.yaml b/actions/import-secret/action.yaml
--- a/actions/import-secret/action.yaml
+++ b/actions/import-secret/action.yaml
@@ -97,98 +97,108 @@ runs:
         echo "EOF" >> $GITHUB_OUTPUT
         
     - name: Export secrets from Secret Manager to sm temp file
-      shell: bash
-      run: | 
-        sm_secrets_file_path=${{ steps.secrets-file.outputs.sm }}
-        gcloud secrets versions access latest \
-        --secret="server" \
-        --project="cch-plat-glb-dev-project-4" > "$sm_secrets_file_path"  
-
-
-    - name: Remove secrets that haven't changed from vault secrets file
-      id: remove-secrets
-      shell: bash
-      run: |
-        VAULT_SECRETS_FILE_PATH=${{ steps.secrets-file.outputs.vault }}
-        SM_SECRETS_FILE_PATH=${{ steps.secrets-file.outputs.sm }}
-
-        vault_key_list=$(yq ". | keys | .[]" $VAULT_SECRETS_FILE_PATH)
-        vault_keys=()
-
-        while IFS= read -r line ; do
-          if [ ! -z "$line" ]; then
-            vault_keys+=("$line")
-          fi
-        done <<< "$vault_key_list"
-
-        sm_key_list=$(yq ". | keys | .[]" $SM_SECRETS_FILE_PATH)
-        sm_keys=()
-
-        while IFS= read -r line ; do 
-          if [ ! -z "$line" ]; then
-            sm_keys+=("$line")
-          fi
-        done <<< "$sm_key_list"
-
-        for vault_key in "${vault_keys[@]}"; do
-          vault_value=$(yq ".$vault_key" $VAULT_SECRETS_FILE_PATH)
-              
-          if [ "$vault_value" == "" ]; then
-              echo "Error - Vault secret has no value. Secret key: $vault_key"
-              exit 1
-          fi
-
-          for sm_key in "${sm_keys[@]}"; do
-            if [ "$vault_key" == "$sm_key" ]; then
-              sm_value=$(yq ".$sm_key" $SM_SECRETS_FILE_PATH)
-
-              if [ "$vault_value" == "$sm_value" ]; then
-                yq -i "del(.$vault_key)" $VAULT_SECRETS_FILE_PATH
-
-                echo "Existing secret with no value change: $vault_key"
-              fi
-              break
-            fi
-          done;
-        done;
-
-        secrets_keys_to_import_count=$(yq ". | keys | length" $VAULT_SECRETS_FILE_PATH)
-        echo "Secret keys count to import: $secrets_keys_to_import_count"
-
-        do_import="false"
-
-        if [ "$secrets_keys_to_import_count" -gt "0" ]; then
-            do_import="true"
-            secrets_keys_to_import=$(yq ". | keys" $VAULT_SECRETS_FILE_PATH)
-
-            echo "Secret keys to import:"
-            echo "$secrets_keys_to_import"
-        fi
-
-        echo "do-import=$do_import" >> "$GITHUB_OUTPUT"
-      
-
-    - name: Import secrets from vault temp file to SM  
-      uses: ./actions/update-secrets
-      if: ${{ steps.remove-secrets.outputs.do-import == 'true' && inputs.import-secrets == 'true' }} 
+      uses: ./actions/export-secrets 
       with:
         app-name: ${{ inputs.one-password-primary-vault }} 
         service-name: ${{ inputs.one-password-primary-item }}
-        secrets-file: ${{ steps.secrets-file.outputs.vault }}
-
-    - name: No new or updated secrets to import
-      if: ${{ steps.remove-secrets.outputs.do-import == 'false' && inputs.import-secrets == 'true' }}
+        secrets-file: ${{ steps.secrets-file.outputs.sm }}
+        vault-env-keys: ${{ steps.envar-key-processor.outputs.yaml-keys }}
+    
+    - name: upload secret file 
       shell: bash
       run: |
-        echo "No secrets to import since there are no new or updated items"
+        ls -la $env:RUNNER_TEMP 
+        VAULT_LOCAL_FILE=$env:RUNNER_TEMP/vault-secrets.yaml
+        SM_LOCAL_FILE=$env:RUNNER_TEMP/sm-secrets.yaml 
+        GCS_BUCKET_PATH="gs://cch-cicd-test/test"
 
-    - name: Importing of secrets disabled
-      if: ${{ steps.remove-secrets.outputs.do-import == 'true' && inputs.import-secrets != 'true' }}
-      shell: bash
-      run: |
-        echo "${{ steps.remove-secrets.outputs.do-import }}"
-        echo "${{ inputs.import-secrets }}"
-        echo "Importing of secrets was disabled but there were new or updated items"
+        gsutil cp "${VAULT_LOCAL_FILE}" "${GCS_BUCKET_PATH}"
+        gsutil cp "${SM_LOCAL_FILE}" "${GCS_BUCKET_PATH}"
+
+    # - name: Remove secrets that haven't changed from vault secrets file
+    #   id: remove-secrets
+    #   shell: bash
+    #   run: |
+    #     VAULT_SECRETS_FILE_PATH=${{ steps.secrets-file.outputs.vault }}
+    #     SM_SECRETS_FILE_PATH=${{ steps.secrets-file.outputs.sm }}
+
+    #     vault_key_list=$(yq ". | keys | .[]" $VAULT_SECRETS_FILE_PATH)
+    #     vault_keys=()
+
+    #     while IFS= read -r line ; do
+    #       if [ ! -z "$line" ]; then
+    #         vault_keys+=("$line")
+    #       fi
+    #     done <<< "$vault_key_list"
+
+    #     sm_key_list=$(yq ". | keys | .[]" $SM_SECRETS_FILE_PATH)
+    #     sm_keys=()
+
+    #     while IFS= read -r line ; do 
+    #       if [ ! -z "$line" ]; then
+    #         sm_keys+=("$line")
+    #       fi
+    #     done <<< "$sm_key_list"
+
+    #     for vault_key in "${vault_keys[@]}"; do
+    #       vault_value=$(yq ".$vault_key" $VAULT_SECRETS_FILE_PATH)
+              
+    #       if [ "$vault_value" == "" ]; then
+    #           echo "Error - Vault secret has no value. Secret key: $vault_key"
+    #           exit 1
+    #       fi
+
+    #       for sm_key in "${sm_keys[@]}"; do
+    #         if [ "$vault_key" == "$sm_key" ]; then
+    #           sm_value=$(yq ".$sm_key" $SM_SECRETS_FILE_PATH)
+
+    #           if [ "$vault_value" == "$sm_value" ]; then
+    #             yq -i "del(.$vault_key)" $VAULT_SECRETS_FILE_PATH
+
+    #             echo "Existing secret with no value change: $vault_key"
+    #           fi
+    #           break
+    #         fi
+    #       done;
+    #     done;
+
+    #     secrets_keys_to_import_count=$(yq ". | keys | length" $VAULT_SECRETS_FILE_PATH)
+    #     echo "Secret keys count to import: $secrets_keys_to_import_count"
+
+    #     do_import="false"
+
+    #     if [ "$secrets_keys_to_import_count" -gt "0" ]; then
+    #         do_import="true"
+    #         secrets_keys_to_import=$(yq ". | keys" $VAULT_SECRETS_FILE_PATH)
+
+    #         echo "Secret keys to import:"
+    #         echo "$secrets_keys_to_import"
+    #     fi
+
+    #     echo "do-import=$do_import" >> "$GITHUB_OUTPUT"
+      
+
+    # - name: Import secrets from vault temp file to SM  
+    #   uses: ./actions/update-secrets
+    #   if: ${{ steps.remove-secrets.outputs.do-import == 'true' && inputs.import-secrets == 'true' }} 
+    #   with:
+    #     app-name: ${{ inputs.one-password-primary-vault }} 
+    #     service-name: ${{ inputs.one-password-primary-item }}
+    #     secrets-file: ${{ steps.secrets-file.outputs.vault }}
+
+    # - name: No new or updated secrets to import
+    #   if: ${{ steps.remove-secrets.outputs.do-import == 'false' && inputs.import-secrets == 'true' }}
+    #   shell: bash
+    #   run: |
+    #     echo "No secrets to import since there are no new or updated items"
+
+    # - name: Importing of secrets disabled
+    #   if: ${{ steps.remove-secrets.outputs.do-import == 'true' && inputs.import-secrets != 'true' }}
+    #   shell: bash
+    #   run: |
+    #     echo "${{ steps.remove-secrets.outputs.do-import }}"
+    #     echo "${{ inputs.import-secrets }}"
+    #     echo "Importing of secrets was disabled but there were new or updated items"
 
     # - name: Delete unneeded secrets from the sm Parameter Store
     #   uses: carecloud/github-action-delete-secrets-ssm@main
